service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct

useDotenv: true  

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getMenu:
    handler: functions/getMenu/index.handler
    events:
      - httpApi:
          path: '/api/menu/{search}'
          method: GET
  
  postMenu:
    handler: functions/postMenu/index.handler
    events:
      - httpApi:
          path: '/api/menu'
          method: POST        
  getOrder:
    handler: functions/getOrder/index.handler
    events:
      - httpApi:
          path: '/api/orders'
          method: GET
  environment:
    ORDER_TABLE: !Ref ordersDb    


resources:
  Resources:
    YumYum:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: YumYumDB
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S  
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

